version: '3'
services:
  cybercoach-labs:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CYBERCOACH_API_KEY=sk_live_892348572345
      - CYBERCOACH_ADMIN_SECRET=SuperSecretBackdoorKey
      - FLAG_MISCONFIG=CYBERCOACH_ENV_LEAKED_SUCCESS
    volumes:
      - ./labs.db:/usr/src/app/labs.db
    restart: always
