services:
  - type: web
    name: sovap-cyberlabs
    env: docker
    plan: free
    branch: main
    envVars:
      - key: SOVAP_API_KEY
        value: sk_live_892348572345
      - key: SOVAP_ADMIN_SECRET
        value: SuperSecretBackdoorKey
      - key: PORT
        value: 3000
